name: climatebench-app
channels:
  - pyviz
dependencies:
  - geoviews-core
  - pip
  - pip:
    - tensorflow==2.10.0
    - xarray
    - streamlit
variables:
  REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
